# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipale', '0004_auto_20170414_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objet',
            name='image',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
