# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipale', '0006_auto_20170415_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objet',
            name='image',
            field=models.ImageField(default='no image', null=True, upload_to='photos/'),
        ),
    ]
