# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipale', '0009_comentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentaire',
            name='titre',
            field=models.CharField(default='Default', max_length=40),
        ),
    ]
