# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-10 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipale', '0015_objet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objet',
            name='photo',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
