# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipale', '0010_profil'),
        ('appPrincipale', '0016_auto_20170510_0848'),
    ]

    operations = [
    ]
