# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipale', '0017_merge_20170511_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='objet',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='user',
        ),
        migrations.AlterField(
            model_name='objet',
            name='photo',
            field=models.ImageField(default='photos/ryan_ygf9Uff.jpg', upload_to='photos/'),
        ),
        migrations.DeleteModel(
            name='Profil',
        ),
    ]
