# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 13:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appPrincipale', '0018_auto_20170511_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentaire',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='objet',
            name='adresse',
            field=models.CharField(default='100 roger salengro', max_length=150),
        ),
    ]
