# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipale', '0019_auto_20170512_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentaire',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de parution'),
        ),
        migrations.AddField(
            model_name='objet',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de parution'),
        ),
    ]
