# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-16 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipale', '0020_auto_20170514_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objet',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
    ]
